name: acpp11-502 exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/gcc11-cmake:4
            options: -u 1001
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: solutions
                fetch-depth: 1  
            - name : build and test Exercise 1
              run: |
                cd solutions/exercise1
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 2
              run: |
                cd solutions/exercise2_gtest
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 4
              run: |
                cd solutions/exercise4_gmock
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 5
              run: |
                cd solutions
                git clone https://github.com/onqtam/doctest.git
                cd exercise5_doctest
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test
            - name : build and test Exercise 6
              run: |
                cd solutions/exercise6_gmock
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test
