name: tddcpp-301 exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            options: -u 1001
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: solutions
                fetch-depth: 1  
            - name : build and test Exercise 1
              run: |
                cd solutions/exercise1
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 2
              run: |
                cd solutions/exercise2_gtest
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 4
              run: |
                cd solutions/exercise4_gmock
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test   
            - name : build and test Exercise 5
              run: |
                cd solutions/exercise5_gmock
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test
            - name : build and test Exercise 6
              run: |
                cd solutions
                git clone https://github.com/onqtam/doctest.git
                cd exercise6_doctest
                cmake -S . -B build
                cmake --build build
                cmake --build build -- test
            - name : build Exercise 1 Template
              run: |
                cd templates/exercise1_gtest/
                cmake -S . -B build
                cmake --build build
                # cmake --build build -- test  
            - name : build Exercise 2 Template
              run: |
                cd templates/exercise2_gtest/
                cmake -S . -B build
                cmake --build build
                # cmake --build build -- test  
            - name : build Exercise 4 Template
              run: |
                cd templates/exercise4_gmock/
                cmake -S . -B build
                cmake --build build
                # cmake --build build -- test  
            - name : build Exercise 6 Template
              run: |
                cd templates/exercise6_doctest/
                git clone https://github.com/onqtam/doctest.git
                cmake -S . -B build
                cmake --build build
                # cmake --build build -- test  